[package]
name = "debuzzy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.8"
regex = "1.6.0"
rayon = "1.5.3"
lazy_static = "1.4"
rustfft = "6.0.1"
realfft = "3.0.0"
